### ISSUE TITLE
Consider using traits from the `aead` crate?

### ISSUE THREAD

**Issue by tarcieri** [martindisch/aes-ccm#2]
Hello! Glad to see there's a Rust implementation of `aes-ccm`, which I may consider using soon for a particular project.

The `aead` crate provides traits which abstract over various AEAD modes:

https://github.com/RustCrypto/traits/tree/master/aead

Namely the `Aead` (and `AeadMut`) traits:

https://docs.rs/aead/latest/aead/trait.Aead.html

As of the 0.2 release, they now support an optional `alloc` feature (in addition to always being `#![no_std]`) along with a `heapless` feature to support usage in heapless (e.g. microcontroller) environments.

Is this something you'd be interested in using? If so, I can send a PR.

**Comment by martindisch** [comment]
Hi Tony, I'm very happy you're interested in doing that. When I first ported this, I did check the RustCrypto traits to see if I could use something like that to provide a reusable interface, but at the time they weren't around yet. Since you're the one who designed them in the first place, you're of course the perfect person to implement them, so I'll gladly accept any related PRs.

**Comment by tarcieri** [comment]
Awesome! I also have an [open PR to mention `heapless` AEAD support in the rust-embedded newsletter](https://github.com/rust-embedded/blog/pull/81/files). Mind if I link to this issue in case people are interested in `aes-ccm` too?

**Comment by martindisch** [comment]
Sure thing! I haven't discovered that newsletter yet, it's nice to see people pushing embedded Rust forward.

**Comment by tarcieri** [comment]
Opened a draft PR for discussion: https://github.com/martindisch/aes-ccm/pull/3

**Comment by tarcieri** [comment]
Closing this as #3 is merged

**Comment by tarcieri** [comment]
@martindisch thanks for merging the PR! I added a link to your crate from the README.md here:

https://github.com/RustCrypto/AEADs

**Comment by martindisch** [comment]
Thanks, that will make it easier to find for people who need it.
